input validation for -lt and -gt, improved stand-alone goop, support negative integers

diff --git a/bashtest b/bashtest
--- a/bashtest
+++ b/bashtest
@@ -3,8 +3,14 @@
 [[() {
   local ret
   local j
-  [ ! "$4" = "]]" ] && return 1
   case "$1" in
+    -*) [ ! "$3" = "]]" ] && return 1 ;;
+  esac
+  case "$2" in
+    -*) [ ! "$4" = "]]" ] && return 1 ;;
+  esac
+  case "$1" in
+    Z) printf 'Usage error\n' >&2 ;;
     -a|-e)	[ -e "$2" ] || ret=1 ;;
     -b|-c|-d|-f|-g|-h|-k|-n|-p|r|-s|-t|-u|-w|-x|-z|-L|-G|-S|-O)
     		[ "$1" "$2" ] || ret=1 ;;
@@ -15,12 +21,19 @@
     -*) ret=64 ;;
   esac
   case "$2" in
+    \<|\>)
+      case "${1}" in [^0-9-]*) return 64 ;; esac
+      case "${3}" in [^0-9-]*) return 64 ;; esac
+      case "${1}" in *[^0-9]*) return 64 ;; esac
+      case "${3}" in *[^0-9]*) return 64 ;; esac
+    ;;
+  esac
+  case "$2" in
     -ef|-nt|-ot) [ "$1" "$2" "$3" ] || ret=1 ;;
     =|==) [ "$1" != "$3" ] && ret=1 ;;
     !=) [ "$1" = "$3" ] && ret=1 ;;
-    \<|\>) expr "${1}${2}" : '.*[^0-9]' >/dev/null && return 64 ;&
-    \<) [ ! "$1" -lt "$3"] && ret=1 ;;
-    \>) [ ! "$1" -gt "$3"] && ret=1 ;;
+    \<) [ ! "$1" -lt "$3" ] && ret=1 ;;
+    \>) [ ! "$1" -gt "$3" ] && ret=1 ;;
     -eq|-ne|-lt|-le|-gt|-ge) [ "$1" "$2" "$3" ] || ret=1 ;;
     ~)
        j="${3#.}"
@@ -36,7 +49,11 @@
   return ${ret:-0}
 }
 
-if [[ "$0" == "${BASH_SOURCE[0]}" ]] || [[ -z "${BASH_SOURCE[0]}" ]]; then
+if [ -n "$BASH_VERSION" ]; then
+  if [[ "$0" == "${BASH_SOURCE[0]}" ]] || [[ -z "${BASH_SOURCE[0]}" ]]; then
     [[ "$@"
+  fi
+elif [ "$0" != sh ]; then
+  [[ "$@"
 fi
 
